name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.prg.github.com
          name: docker.pkg.github.com/osadchii/market-bus/market-bus
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "market-bus"
